version: '3.8'

services:
  web:
    build:
      context: ../..
      dockerfile: ./apps/web/Dockerfile
    ports:
      - '3003:3003'
    env_file:
      - .env.development
    command: npm run start
